create table COURSE_INFO
(
  COURSE_CODE INT,
  COURSE VARCHAR(20),
  COURSE_DESCRIPTION VARCHAR(20),
  COURSE_START_DATE DATE
  
);

ALTER TABLE COURSE_INFO
MODIFY (
        COURSE_CODE VARCHAR(5),
        COURSE_DESCRIPTION VARCHAR(200)
        );

ALTER TABLE COURSE_INFO
ADD (
        COURSE_DURATION NUMBER(1,5),
        NUMBER_OF_PARTICIPANTS NUMBER(1,5),
        COURSE_TYPE CHARACTER(3)
        );

ALTER TABLE COURSE_INFO
RENAME 
        COLUMN COURSE TO COURSE_NAME;

ALTER TABLE COURSE_INFO 
RENAME TO CMS_COURSE_INFO;

DROP TABLE CMS_COURSE_INFO;

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(343,'JAVA PROGRAMMING', 'BASICS OF JAVA', TO_DATE('12/12/2012','MM/DD/YYYY'));

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(167,'C PROGRAMMING', 'BASICS OF C', TO_DATE('11/11/2012','MM/DD/YYYY'));

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(347,'RDMS', 'BASICS OF RDMS', TO_DATE('11,12,1990','MM/DD/YYYY'));

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(106,'ORACLE', 'ORACLE SQL', TO_DATE('11/03/2011','MM/DD/YYYY'));

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(343,'JAVA PROGRAMMING', 'BASICS OF JAVA', TO_DATE('12/12/2012','MM/DD/YYYY'));

UPDATE COURSE_INFO
SET COURSE_NAME = 'MYSQL'
WHERE COURSE_CODE = 106;

DELETE FROM COURSE_INFO
WHERE COURSE_NAME = 'RDMS'

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(106,'ORACLE', 'ORACLE PL SQL', TO_DATE('11,03,2011','MM/DD/YYYY'));

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(302,'ORACLE', 'ORACLE ARCHITECTURE', TO_DATE('11/04/2011','MM/DD/YYYY'));

INSERT INTO COURSE_INFO(COURSE_CODE,COURSE_NAME,COURSE_DESCRIPTION,COURSE_START_DATE)
VALUES(231,'CORE JAVA', 'JAVA IO', TO_DATE('11/06/2011','MM/DD/YYYY'));

SELECT * FROM COURSE_INFO
WHERE COURSE_NAME = 'CORE JAVA'

SELECT * FROM COURSE_INFO
WHERE COURSE_NAME = 'CORE JAVA' AND COURSE_CODE = 343

SELECT DISTINCT(COURSE_NAME) FROM COURSE_INFO
