package corejava.utils;

public class OracleQueries {

	public final static String GETSTUDENTBYGMAIL = "SELECT * FROM STUDENT "
			+ "WHERE EMAIL = ? ORDER BY STUDENT_ID ASC";
	
	public final static String GETINSTRUCTORBYGMAIL = "SELECT * FROM INSTRUCTOR "
			+ "WHERE EMAIL = ? ORDER BY INSTRUCTOR_ID ASC";
	
	public final static String GETALLINSTRUCTOR = "SELECT * FROM INSTRUCTOR "
			+ "ORDER BY INSTRUCTOR_ID ASC";
	
	public final static String GETCOURSEBYINSTRUCTOR = "SELECT COURSE.COURSE_ID, COURSE.COURSE_NAME, COURSE.MINIMUN_GPA "
			+ "FROM COURSE JOIN TEACHING ON COURSE.COURSE_ID = TEACHING.COURSE_ID "
			+ "WHERE INSTRUCTOR_ID = ? ORDER BY COURSE_ID ASC";
	
	public final static String GETALLCOURSE = "SELECT * FROM COURSE "
			+ "ORDER BY COURSE_ID ASC";
	
	
	public final static String REGISTERSTUDENTOCOURSE = "INSERT INTO ATTENDING(COURSE_ID,STUDENT_ID) "
			+ "VALUES(?,?)";
	
	public final static String GETSTUDENTCOURSE = "SELECT COURSE.COURSE_NAME, STUDENT.FULL_NAME, STUDENT.EMAIL "
			+ "FROM STUDENT JOIN ATTENDING ON ATTENDING.STUDENT_ID = STUDENT.STUDENT_ID "
			+ "JOIN COURSE ON COURSE.COURSE_ID = ATTENDING.COURSE_ID "
			+ "WHERE STUDENT.STUDENT_ID = ?";
	
	public final static String REGISTERINSTRUCTORTOCOURSE = "INSERT INTO TEACHING(COURSE_ID, INSTRUCTOR_ID) "
			+ "VALUES(?,?)";

	public final static String GETINSTRUCTORCOURSES = "SELECT COURSE.COURSE_NAME,COURSE.MINIMUN_GPA, INSTRUCTOR.FULL_NAME, INSTRUCTOR.EMAIL "
			+ "FROM INSTRUCTOR JOIN TEACHING ON TEACHING.INSTRUCTOR_ID = INSTRUCTOR.INSTRUCTOR_ID "
			+ "JOIN COURSE ON COURSE.COURSE_ID = TEACHING.COURSE_ID ";	
	
	
	//INSERT INTO TEACHING(course_id, instructor_id) VALUES(1,1);
	
//	public final static String UPDATEITEMQUANTITY= "UPDATE ITEM_TABLE "
//			+ "SET QUANTITY_IN_STOCK = QUANTITY_IN_STOCK - ? WHERE ITEM_ID = ?";
//	
//	public final static String CREATEORDER = "INSERT INTO ORDER_TABLE "
//			+ "(ITEM_ID, QUANTITY) "
//			+ "VALUES(?,?)";
//}
}